/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void timerStartStopClicked(GButton source, GEvent event) { //_CODE_:timerStartStop:529884:
  paused = false;
} //_CODE_:timerStartStop:529884:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  timerStartStop = new GButton(this, 462, 423, 80, 30);
  timerStartStop.setText("START");
  timerStartStop.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  timerStartStop.addEventHandler(this, "timerStartStopClicked");
}

// Variable declarations 
// autogenerated do not edit
GButton timerStartStop; 
